spin_manifest_version = 2

[application]
authors = ["macolso <mackenzie.olson@fermyon.com>"]
description = "Static webpage built with Zola framework"
name = "zola-blog"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "zola-blog"

[component.zola-blog]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.0.3/spin_static_fs.wasm", digest = "sha256:38bf971900228222f7f6b2ccee5051f399adca58d71692cdfdea98997965fd0d" }
files = [{ source = "public", destination = "/" }]
[component.zola-blog.build]
command = "zola build"
